---
- hosts: all
  connection: local
  
  tasks:
  - name: Install nginx
    become: true
    apt:
      name:
        - nginx
  - name: Install nginx.conf for reverse proxy
    become: true
    template:
      src: reverse-proxy.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'
  - name: Restart nginx
    become: true
    systemd:
      state: restarted
      name: nginx